/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlanesRouteImport } from './routes/planes'
import { Route as PublicarRouteImport } from './routes/publicar'
import { Route as PropiedadesIndexRouteImport } from './routes/propiedades.index'
import { Route as PropiedadesIdRouteImport } from './routes/propiedades.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanesRoute = PlanesRouteImport.update({
  id: '/planes',
  path: '/planes',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicarRoute = PublicarRouteImport.update({
  id: '/publicar',
  path: '/publicar',
  getParentRoute: () => rootRouteImport,
} as any)
const PropiedadesIndexRoute = PropiedadesIndexRouteImport.update({
  id: '/propiedades/',
  path: '/propiedades/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropiedadesIdRoute = PropiedadesIdRouteImport.update({
  id: '/propiedades/$id',
  path: '/propiedades/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/planes': typeof PlanesRoute
  '/publicar': typeof PublicarRoute
  '/propiedades/$id': typeof PropiedadesIdRoute
  '/propiedades/': typeof PropiedadesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/planes': typeof PlanesRoute
  '/publicar': typeof PublicarRoute
  '/propiedades/$id': typeof PropiedadesIdRoute
  '/propiedades': typeof PropiedadesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/planes': typeof PlanesRoute
  '/publicar': typeof PublicarRoute
  '/propiedades/$id': typeof PropiedadesIdRoute
  '/propiedades/': typeof PropiedadesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/planes' | '/publicar' | '/propiedades/$id' | '/propiedades/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/planes' | '/publicar' | '/propiedades/$id' | '/propiedades'
  id:
    | '__root__'
    | '/'
    | '/planes'
    | '/publicar'
    | '/propiedades/$id'
    | '/propiedades/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlanesRoute: typeof PlanesRoute
  PublicarRoute: typeof PublicarRoute
  PropiedadesIdRoute: typeof PropiedadesIdRoute
  PropiedadesIndexRoute: typeof PropiedadesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planes': {
      id: '/planes'
      path: '/planes'
      fullPath: '/planes'
      preLoaderRoute: typeof PlanesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicar': {
      id: '/publicar'
      path: '/publicar'
      fullPath: '/publicar'
      preLoaderRoute: typeof PublicarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propiedades/': {
      id: '/propiedades/'
      path: '/propiedades'
      fullPath: '/propiedades/'
      preLoaderRoute: typeof PropiedadesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propiedades/$id': {
      id: '/propiedades/$id'
      path: '/propiedades/$id'
      fullPath: '/propiedades/$id'
      preLoaderRoute: typeof PropiedadesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlanesRoute: PlanesRoute,
  PublicarRoute: PublicarRoute,
  PropiedadesIdRoute: PropiedadesIdRoute,
  PropiedadesIndexRoute: PropiedadesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
